### ISSUE TITLE
Beans, Contexts, and EL org.jboss.cdi.tck.spi integration interfaces

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/cdi-tck#340]
Need to look at tests that are using the Beans, Contexts, and EL org.jboss.cdi.tck.spi integration interfaces that are not currently in a cdi-full test group.

**Comment by Ladicek** [comment]
I think the most important is the `EL` interface, because CDI Lite doesn't depend on EL (at least that has been my running assumption).

Similar situation is the `Beans.passivate` and `activate` methods, that's also out of the Lite scope. The other methods on `Beans`, as well as all the `Contexts` methods, should be fine for Lite.

**Comment by manovotn** [comment]
Going through the tests, I agree that `Contexts` util class is fine and doesn't hurt in Lite.

Most of EL has been taken care of but I found one more which I think is misplaced.
And then there is `Beans` with its passivation/activation calls. Some are on req. scoped beans which are part of Lite but from what I recall we deliberately avoid mentioning passivation there, so I'd mark them as Full as well.

I'll double check my changes and send a PR shortly.
