### ISSUE TITLE
Confusing usage of `RequestScoped` in `BuiltinInstanceDependentObjectTest` 

### ISSUE THREAD

**Issue by dstepanov** [eclipse-ee4j/cdi-tck#357]
I'm trying to understand how the request scope is supposed to work after hitting the problem with:

```java
package org.jboss.cdi.tck.tests.context.dependent.instance;

@RequestScoped
public class Bar {

    public void observeGoodEvents(Instance<Foo> instance, @Observes GoodEvent goodEvent) {
        instance.get().ping();
    }

}
```

Spec defines when request scope is active:

```
The request context is active:

    - during notification of an asynchronous observer method, and

    - during @PostConstruct callback of any bean.

```

And the definition of the async observer method:

```
If @Observes is used the observer method is a synchronous observer method.

If @ObservesAsync is used the observer method is an asynchronous observer method.
```

So I'm not really sure if this case is correct according to the spec.

Also, it would be nice if request scope tests were in a separate package and not mixed with other scenarios.

**Comment by manovotn** [comment]
> I'm trying to understand how the request scope is supposed to work after hitting the problem with:

I think this is the case of observer method notification.
The spec talks about this here - https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#observer_notification
And it also mentions invocation of OM here - https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#observers_method_invocation

In short, you need to create an instance of that bean in order to be able to notify it (assuming `Reception` is `ALWAYS` which is the case here) and the spec doesn't say that inactive scope prevents you from doing that.

> Also, it would be nice if request scope tests were in a separate package and not mixed with other scenarios.

Packages usually correspond to what they test. But since you are in CDI, you will need to use some scope annotation (or rather even multiple)  in every single test. That would make such packaging really hard to achieve.

**Comment by dstepanov** [comment]
I meant to have a separate test that tests things around request scope

**Comment by manovotn** [comment]
So, after a discussion with Martin and Ladislav, this test is actually only passing in current implementations because of Arq. adapter automatically activating req. scope for test methods (due to various reasons; be it mocking the real environment or because it is over a servlet protocol etc).

So changing the bean to app scope should be a way to go because there is nothing in this test that requires req. scope bean anyway.

**Comment by manovotn** [comment]
Not that I know of, but I am releasing RC-7 as we speak because that's needed for ballot rerun (due to the missing test for newly added `Startup`/`Shutdown` events). So expect it in Central within an hour.
